### ISSUE TITLE
Admirals

### ISSUE THREAD

**Issue by morvael** [BSData/dropfleet-commander#4]
@Jonskichov, @amis92 looking for your advice how to best handle admirals in this game. The problem is I need those admirals (of various power levels) to be upgrades for individual ships (models), but their cost depends on ship category/profile value of the ship they are attached to, and their cost must not be added to ship value, but to the roster/force value. For now this is solved in such a way, so that there are multiple instances of admirals at the same power level that cost 0 points, and the Fleet special entry modifies its cost by counting those admirals by their unique UUIDs. So that in the GUI one admiral looks like another of the same power level, but they are different entities, so that their cost can be counted properly. Is there a better way to solve this?

**Comment by amis92** [comment]
I'll have a look when I have some free time, maybe tomorrow

**Comment by morvael** [comment]
Thanks.

I think it would be an useful addition to be able to specify in an entry on which level its cost should be applied: Parent, Model, Unit, Force, Roster etc.

**Comment by morvael** [comment]
Reworked admirals, so that now a Flagship (free ship upgrade) is selected separately from Admiral (paid Fleet entry upgrade).
