### ISSUE TITLE
Updates to Fleet Lists

### ISSUE THREAD

**Issue by solarsky91** [BSData/dropfleet-commander#5]
Earlier this year (2020), TTC Combat pushed out an update to all the fleet lists in Dropfleet Commander. They have also added in a new ship class called 'Lighter'. Requesting updates to be made or I can step in and assist with the update.

**Comment by morvael** [comment]
Will do, except going on 10 day vacation right now where it will be impossible.

**Comment by LockeWatts** [comment]
What is the status of this ticket? It's nearly 3 months old. This is a thing I can assist with if needed.

**Comment by morvael** [comment]
How can I add you as author in this repository?

**Comment by Giftgruen** [comment]
Data files have now been updated to v1.3.1. Please report any inaccuracy you find!
