### ISSUE TITLE
[Join Request] Update to Version 1.3.1

### ISSUE THREAD

**Issue by Giftgruen** [BSData/dropfleet-commander#6]
Hello,

I would like to contribute to this data repository and update the ship statistics to the latest version, including adding the new lighters / cutters and battlecruisers which have been released since the last data update in 2019. Especially the Resistance roster has seen extensive additions and heavier ships of all factions have had points cost adjustments.

I already have up-to-date data files (barring any mistakes on my part) which I would like to integrate into this repository.

**Comment by DrTobogganMD** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/2191483229)
:robot: Invited @Giftgruen with **push** access. Invite can be accepted on https://github.com/BSData/dropfleet-commander/invitations
