### ISSUE TITLE
[Anon] Bug report: Scourge - 1st Edition - 2016.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dropfleet-commander#7]
**File:** Scourge - 1st Edition - 2016.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** The battlescribe datafiles have shenlong heavy crusiers at 160 points, but tt combat, and the official fleet builder, has them at 170 points. Love your work but please correct this error.

**Comment by Giftgruen** [comment]
Thank you, will fix!

**Comment by Giftgruen** [comment]
I just checked and the official fleet builder ( https://dropfleetcommander.com/builder/ ) has them at 160 pts.

**Comment by Giftgruen** [comment]
Does not need fixing since the price corresponds to the latest fleetbuilder data which TTCombat stated should be seen as the most up-to-date source in case of conflicts.
