### ISSUE TITLE
Data somewhat outdated.

### ISSUE THREAD

**Issue by WeissRaben90** [BSData/dropfleet-commander#8]
The last release for this data was in February, but a new edition of the FAQ & Errata document was released in June, which includes a large slew of changes to various ships and weapons in the game.

https://cdn.shopify.com/s/files/1/0965/1274/files/Dropfleet_Commander_FAQ_v2.5.pdf?v=1685967628
(Page 24 and onwards.)

My question is whether this project is abandoned, making any hope of seeing these updates pretty much moot, or if they will be implemented at some point (personal time and effort allowing, it goes without saying).

**Comment by Kemp-J** [comment]
I have now created [this milestone](https://github.com/BSData/dropfleet-commander/milestone/1) to track work towards updating the data to match the latest published information.
